---
title: "RNA seq batch correction using metadata"
author: "Nick Hirschmuller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
always_allow_html: yes
output:
  html_document:
    word_document:
    toc: yes
    toc_depth: '3'
    code_folding: hide
  pdf_document:
    number_sections: yes
    toc: false
    toc_depth: 3
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = T, warning = F, error = F, message = F,
    fig.align = "center", cache = F, dpi = 150
)
```

## **Introduction**
Just out of interest, remove the samples that Maria removed and then redo adjustment. 

```{r, load libraries}
library(DESeq2)
library(ComplexHeatmap)
library(RColorBrewer)
library(circlize)
library(magrittr)
library(PCAtools)
library(umap)
library(patchwork)
library(sva)
library(clusterProfiler)
library(RUVSeq)
library(httpgd)
library(tidyverse)
library(Rtsne)

library(here)
source(here("plot_theme.R"))
source(here("helper_functions.R"))
```


## Adjust count data
```{r}
# for creation see script **01_initial_QC.rmd**
dds <- readRDS(here("QC", "results", "dds_libsize_outliers_removed.rds"))
samples_remove <- data.table::fread(here("data", "Maria_samples_to_remove.txt"), header = T, data.table=F)[,1]
dds <- dds[,!dds$sampleid %in% samples_remove]
mdata <- colData(dds) %>% data.frame()

# regress out donor effect (cell line)
# use limmas removeBatchEffects to emulate what the linear model will eventually do.
mod <- model.matrix(~group, colData(dds))
norm_cnts <- assay(vst(dds))
adjusted_counts <- limma::removeBatchEffect(norm_cnts,
    batch = dds$line, 
    design = mod
)

#################
# CALCULATE PCA #
#################
pca_data <- PCAtools::pca(adjusted_counts,
    metadata = colData(dds),
    removeVar = 0.4
)
pca_plot_df <- pca_data$rotated[, 1:20] %>%
    rownames_to_column("sample_id") %>%
    left_join(., colData(dds) %>% data.frame(), by = c("sample_id" = "sampleid"))
for (i in 1:20) {
    pca_plot_df[, str_interp("PC${i}_explained_var")] <- pca_data$variance[i]
}

PC_pairings <- lapply(1:3, function(x){
    c(2*x-1,2*x)
})
pca_plots <- lapply(PC_pairings, function(i) {
    print(str_interp("Working on PC${i[1]} and PC${i[2]}"))
    plots <- lapply(c("state", "condition", "sex", "ethnicity", "age", "batch1id"), function(x) {
        expl_var1 <- round(pca_plot_df[1, str_interp("PC${i[1]}_explained_var")], 2)
        expl_var2 <- round(pca_plot_df[1, str_interp("PC${i[2]}_explained_var")], 2)
        p <- density_scatter(
            df = pca_plot_df,
            x_variable = str_interp("PC${i[1]}"),
            y_variable = str_interp("PC${i[2]}"),
            color_by = x,
            density_plot_ratio = 0.15,
            pt_size = 1.2,
            xlab = str_interp("PC${i[1]}: ${expl_var1}% variance"),
            ylab = str_interp("PC${i[2]}: ${expl_var2}% variance")
        )
        p <- p +
            plot_annotation(
                title = x,
                theme = theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 20))
            )
        return(p)
    })
    final_plot <- cowplot::plot_grid(plotlist = plots, ncol = 3)
})

# honestly I barely notice any difference... 
pca_plots[[1]]
pca_plots[[2]]


##################
# CALCULATE UMAP #
##################
columns_to_plot <- c("state", "condition", "sex", "ethnicity", "age", "batch1id")
umap_data <- umap(t(adjusted_counts))
umap_plot_df <- umap_data$layout %>%
    data.frame() %>%
    magrittr::set_colnames(c("UMAP1", "UMAP2")) %>%
    rownames_to_column("sampleid") %>%
    left_join(., mdata)

umap_plots <- lapply(columns_to_plot, function(x) {
    p <- density_scatter(
        df = umap_plot_df,
        x_variable = "UMAP1",
        y_variable = "UMAP2",
        color_by = x,
        density_plot_ratio = 0.15,
        pt_size = 1.2,
    )
    p <- p +
        plot_annotation(
            title = x,
            theme = theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 20))
        )
    return(p)
})
final_plot <- cowplot::plot_grid(plotlist = umap_plots, ncol = 3)
final_plot

##################
# CALCULATE TSNE #
##################
columns_to_plot <- c("state", "condition", "sex", "ethnicity", "age", "batch1id")
tsne_data <- Rtsne::Rtsne(t(adjusted_counts))
tsne_plot_df <- tsne_data$Y %>%
    data.frame() %>%
    magrittr::set_colnames(c("TSNE1", "TSNE2")) %>%
    mutate("sampleid" = colnames(adjusted_counts)) %>%
    left_join(., mdata)

tsne_plots <- lapply(columns_to_plot, function(x) {
    p <- density_scatter(
        df = tsne_plot_df,
        x_variable = "TSNE1",
        y_variable = "TSNE2",
        color_by = x,
        density_plot_ratio = 0.15,
        pt_size = 1.2,
    )
    p <- p +
        plot_annotation(
            title = x,
            theme = theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 20))
        )
    return(p)
})

final_plot <- cowplot::plot_grid(plotlist = tsne_plots, ncol = 3)
final_plot
```


### Do ORA to see what PC1 and PC2 correspond to
```{r}
# this is needed for the enrichment analysis that we are doing.
hs_msigdb_df <- msigdbr::msigdbr(species = "Homo sapiens")

gene_sets <- hs_msigdb_df %>%
    filter(gs_subcat == "GO:BP" | gs_cat == "H" | gs_subcat == "CP:KEGG") %>%
    select(gs_name, gene_symbol)


# Extract the genes which most influence PC1 and PC2 and see if they are enriched in any biological domain:
ORA_results <- parallel::mclapply(1:4, function(z) {
    print(paste("Running ORA for PC", z))
    # extract top 300 genes which most influence PC
    top_loadings_gene_names <- pca_data$xvars[order(
        abs(pca_data$loadings[, paste0("PC", z)]),
        decreasing = T
    )[1:300]]

    enrichment_result <- enricher(
        gene = top_loadings_gene_names,
        universe = rownames(dds),
        minGSSize = 5,
        maxGSSize = 300,
        TERM2GENE = gene_sets
    )

    # for each of the biological domains, grep the top 3 sig. terms
    sig_results <- enrichment_result@result %>%
        mutate(domain = str_extract(Description, "^[^_]*")) %>%
        mutate(ratio_numeric = sapply(.$GeneRatio, function(x) {
            eval(
                str2expression(x)
            )
        })) %>%
        filter(p.adjust < 0.05) %>%
        group_by(domain) %>%
        slice_min(., order_by = p.adjust, n = 3) %>%
        mutate(Description_short = shorten_strings(Description, 30))

    if (nrow(sig_results) > 0) {
        enrichment_plot <- ggplot(sig_results, aes(x = ratio_numeric, y = Description_short, color = p.adjust)) +
            geom_segment(aes(
                x = 0, xend = ratio_numeric, y = Description_short, yend = Description_short
            ), color = "black", linewidth = 1.5) +
            geom_point(size = 5) +
            scale_color_gradient(low = "red", high = "blue") +
            theme_Publication_side() +
            ylab("Description") +
            xlab("Gene Ratio") +
            scale_x_continuous(expand = c(0, 0.01))
    } else {
        enrichment_plot <- ggplot() +
            theme_void()
    }
    return(enrichment_plot)

}, mc.cores=10)
names(ORA_results) <- paste0("PC",1:4)
# maybe not ideal... PC3 and PC4 are decent though (but not a lot of variance)
ORA_results$PC1
ORA_results$PC2
ORA_results$PC3
ORA_results$PC4
```

### Conclusion
Again, no big difference. I will stick with the simple method for now. 

```{r}
sessionInfo()
```


