---
title: "Try sex inference"
author: "Nick Hirschmuller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
always_allow_html: yes
output:
  html_document:
    word_document:
    toc: yes
    toc_depth: '3'
    code_folding: hide
  pdf_document:
    number_sections: yes
    toc: false
    toc_depth: 3
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = T, warning = F, error = F, message = F,
    fig.align = "center", cache = F, dpi = 150
)
```

```{r, load libraries}
library(glmnet)
library(DESeq2)
library(tidyverse)
library(caret)
library(glmnet)
library(here)
library(httpgd)

source(here("plot_theme.R"))
source(here("helper_functions.R"))
```


## **Introduction**
Try and use the [SexInference](https://github.com/SexChrLab/SexInference) scripts to infer sex of our people (look for mismatches).


#### Setup our data
```{r}
# the script needs the output from salmon
dds <- readRDS( here("QC", "results", "dds_final.rds"))
mdata <- colData(dds) %>% data.frame()

raw_counts <- data.table::fread(
    here("preprocessing", "results", "gene_counts_length_scaled_filtered.tsv")
) %>% data.frame()
raw_counts_matrix <- as.matrix(raw_counts[,2:ncol(raw_counts)])
rownames(raw_counts_matrix) <- raw_counts$gene_name
raw_counts_matrix <- raw_counts_matrix[, dds$sampleid]
```


#### Load the package data and train the glm
```{r}
training_model_data = "/rds/user/nh608/hpc-work/software/SexInference/RNAseq/training_data/for_rna_sex_check.tsv"
data <- data.table::fread(training_model_data, data.table = FALSE)
# Split the data into training and test set
set.seed(123)
training.samples <- data$sex %>% 
  createDataPartition(p = 0.8, list = FALSE)
train.data  <- data[training.samples, ]
test.data <- data[-training.samples, ]

# remove label
x <- train.data[, -ncol(train.data)] %>% as.matrix()
# Convert the outcome (class) to a numerical variable
y <- ifelse(train.data$sex == "female", 1, 0)
cv.lasso <- cv.glmnet(x, y, alpha = 1, family = "binomial")

# Final model with lambda.min
lasso.model <- glmnet(x, y,
    alpha = 1, family = "binomial",
    lambda = cv.lasso$lambda.min
)

# Make prediction on test data
x.test <- test.data[, -ncol(test.data)] %>% as.matrix()
probabilities <- lasso.model %>% predict(newx = x.test, type="response")
predicted.classes <- ifelse(probabilities > 0.5, "female", "male")
# Model accuracy
observed.classes <- test.data$sex
mean(predicted.classes == observed.classes)

our_data <- t(raw_counts_matrix[c("XIST", "EIF1AY", "KDM5D", "UTY", "DDX3Y", "RPS4Y1"), ]) %>% as.matrix()
probabilities <- lasso.model %>% predict(newx = our_data, type="response")
predicted.classes <- ifelse(probabilities > 0.5, "Female", "Male") %>% data.frame()
```


### Add the predicted sex to the mdata
```{r}
all(rownames(predicted.classes) == mdata$sampleid)
mdata <- predicted.classes %>%
    rownames_to_column("sampleid") %>%
    dplyr::rename(predicted_sex = s0) %>%
    left_join(mdata, ., by = "sampleid")


# for 41 lines there is an apparent sex mismatch which seems very high
mdata %>%
    distinct(line, .keep_all = TRUE) %>%
    filter(sex != predicted_sex) %>% nrow()



# visualize the expression of these genes and the missannotated samples:

# for each celline, calculate the average expression of these genes for all conditions
plot_data <- log1p(counts(dds, normalized = T)[c("DDX3Y", "EIF1AY", "LINC00278", "RPS4Y1", "TXLNGY", "USP9Y", "UTY", "XIST"), ]) %>%
    t() %>%
    data.frame() %>%
    rownames_to_column("sampleid") %>%
    pivot_longer(., cols = !sampleid, values_to = "norm_cnts", names_to = "gene") %>%
    left_join(., mdata %>% select(sampleid, line, sex, predicted_sex), by = "sampleid") %>%
    group_by(line, gene) %>%
    mutate(mean_expr = mean(norm_cnts)) %>%
    ungroup() %>%
    distinct(gene, line, mean_expr, .keep_all = TRUE)

plot_data$mismatch <- case_when(
    plot_data$sex == "Male" & plot_data$predicted_sex == "Female" ~ "Predicted Female",
    plot_data$sex == "Female" & plot_data$predicted_sex == "Male" ~ "Predicted Male"
)

p<-ggplot(plot_data, aes(x = sex, y = mean_expr, color = mismatch)) +
    ggbeeswarm::geom_quasirandom(width = 0.15, size = 0.4) +
    facet_wrap(~gene, scales = "free_y") +
    theme_Publication() +
    stat_summary(
        fun = "mean",
        geom = "crossbar",
        color = "darkgreen",
        width = 0.05,
        aes(group = sex),
        position = position_dodge(width = 0.5)
    ) +
    scale_color_manual(values = c("red", "#0011ff")) 

ggsave(
    plot = p,
    filename = here("sex_inference", "results", "prediction_boxplots.png"),
    width = 7,
    height = 5,
    dpi = 350,
    scale = 1.35
)


ggplot(plot_data, aes(x = predicted_sex, y = mean_expr, color = mismatch)) +
    geom_jitter(width = 0.1) +
    facet_wrap(~gene, scales = "free_y") +
    theme_Publication() +
    stat_summary(
        fun = "mean",
        geom = "crossbar",
        color = "darkgreen",
        width = 0.05,
        aes(group = predicted_sex),
        position = position_dodge(width = 0.5)
    ) +
    scale_color_manual(values = c("black", "red")) +
    theme(legend.position = "none")



# check the training data
traing_data_plot <- data %>% 
    rownames_to_column() %>%
    rowwise() %>%
    mutate(libsize = sum(c_across(XIST:RPS4Y1))) %>% 
    mutate(across(XIST:RPS4Y1, ~ ./libsize)) %>% # normalize the counts by libsize 
    pivot_longer(., cols = XIST:RPS4Y1, values_to = "cnts", names_to = "gene")  


ggplot(traing_data_plot , aes(x = sex, y = cnts))+
    geom_jitter(width = 0.1) +
    facet_wrap(~gene, scales = "free_y") +
    theme_Publication() +
    stat_summary(
        fun = "mean",
        geom = "crossbar",
        color = "darkgreen",
        width = 0.05,
        aes(group = sex),
        position = position_dodge(width = 0.5)
    ) +
    theme(legend.position = "none")
```



### Get external information
```{r}
mdata_hipsci_donor <- data.table::fread(
    here("data", "oxLDL_data", "HipSci", "HipSci_donors.tsv")
) %>% data.frame()

mdata_hipsci_donor$Name <- mdata_hipsci_donor$Name %>%
    str_remove_all(., "HPSI-") %>%
    unique()

mdata_hipsci_donor <- mdata_hipsci_donor %>% distinct(Name, .keep_all = TRUE)

mdata_oxldl <- mdata %>% distinct(line, .keep_all=TRUE)
mdata_oxldl$hipsci_donor <- substr(mdata_oxldl$line, 1, 4) 

mdata_oxldl <-  mdata_oxldl %>%
    left_join(., mdata_hipsci_donor %>%
        select(hipsci_sex = Sex, Name),
    by = c("hipsci_donor" = "Name")
    )

# all match the downloaded ressource. 
table(mdata_oxldl$sex == mdata_oxldl$hipsci_sex)
```


### see if the gender mismatch are the same as in the SV plot
During our QC we noticed some samples that seemed to be in the wrong cloud in the SV plot.
```{r}
## recreate the SV plot
svseq <- readRDS(here("QC", "results", "sva_5_final.rds"))
SVs <- svseq$sv
colnames(SVs) <- paste0("SV", 1:5)
mdata <- cbind(mdata, SVs)
mdata$mismatch <-  ifelse(mdata$sex != mdata$predicted_sex, "mismatch", "match")

ggplot(mdata, aes(SV1, SV2, color = sex)) +
    geom_point(size = 3) +
    geom_point(
        data = mdata %>% filter(mismatch == "mismatch"), aes(SV1, SV2), color = "red", shape = 21,
        stroke = 2, size = 3.3, inherit.aes = FALSE, show.legend = FALSE
    ) +
    theme_Publication() +
    chameleon::scale_color_chameleon()



ggplot(mdata, aes(SV1, SV2, color = predicted_sex)) +
    geom_point(size = 3) +
    geom_point(
        data = mdata %>% filter(mismatch == "mismatch"), aes(SV1, SV2), color = "red", shape = 21,
        stroke = 2, size = 3.3, inherit.aes = FALSE, show.legend = FALSE
    ) +
    theme_Publication() +
    chameleon::scale_color_chameleon()




 

table(mdata$sex)
table(mdata$predicted_sex)

```

