---
title: "Try sex inference"
author: "Nick Hirschmuller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
always_allow_html: yes
output:
  html_document:
    word_document:
    toc: yes
    toc_depth: '3'
    code_folding: hide
  pdf_document:
    number_sections: yes
    toc: false
    toc_depth: 3
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = T, warning = F, error = F, message = F,
    fig.align = "center", cache = F, dpi = 150
)
```

```{r, load libraries}
library(glmnet)
library(DESeq2)
library(tidyverse)

library(here)
source(here("plot_theme.R"))
source(here("helper_functions.R"))
```


## **Introduction**
Try and use the [SexInference](https://github.com/SexChrLab/SexInference) scripts to infer sex of our people (look for mismatches).


#### Setup our data
```{r}
# the script needs the output from salmon
dds <- readRDS( here("QC", "results", "dds_final.rds"))
mdata <- colData(dds) %>% data.frame()

raw_counts <- data.table::fread(
    here("preprocessing", "results", "gene_counts_length_scaled_filtered.tsv")
) %>% data.frame()
raw_counts_matrix <- as.matrix(raw_counts[,2:ncol(raw_counts)])
rownames(raw_counts_matrix) <- raw_counts$gene_name

raw_counts_matrix <- raw_counts_matrix[, dds$sampleid]


```


#### Load the package data and train the glm
```{r}
library(caret)
training_model_data = "/rds/user/nh608/hpc-work/software/SexInference/RNAseq/training_data/for_rna_sex_check.tsv"
data <- data.table::fread(training_model_data, data.table = FALSE)
# Split the data into training and test set
set.seed(123)
training.samples <- data$sex %>% 
  createDataPartition(p = 0.8, list = FALSE)
train.data  <- data[training.samples, ]
test.data <- data[-training.samples, ]

# remove label
x <- train.data[, -ncol(train.data)] %>% as.matrix()
# Convert the outcome (class) to a numerical variable
y <- ifelse(train.data$sex == "female", 1, 0)
cv.lasso <- cv.glmnet(x, y, alpha = 1, family = "binomial")
plot(cv.lasso)
cv.lasso$lambda.min

coef(cv.lasso, cv.lasso$lambda.min)
coef(cv.lasso, cv.lasso$lambda.1se)

# Final model with lambda.min
lasso.model <- glmnet(x, y,
    alpha = 1, family = "binomial",
    lambda = cv.lasso$lambda.min
)

# Make prediction on test data
x.test <- test.data[, -ncol(test.data)] %>% as.matrix()
probabilities <- lasso.model %>% predict(newx = x.test, type="response")
predicted.classes <- ifelse(probabilities > 0.5, "female", "male")
# Model accuracy
observed.classes <- test.data$sex
mean(predicted.classes == observed.classes)



our_data <- t(raw_counts_matrix[c("XIST", "EIF1AY", "KDM5D", "UTY", "DDX3Y", "RPS4Y1"), ]) %>% as.matrix()
probabilities <- lasso.model %>% predict(newx = our_data, type="response")
predicted.classes <- ifelse(probabilities > 0.5, "Female", "Male") %>% data.frame()
all(rownames(predicted.classes) == colnames(dds))

table(predicted.classes[, 1] == dds$sex)




```



