---
title: "RNA seq differential gene expression"
author: "Nick Hirschmuller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
always_allow_html: yes
output:
  html_document:
    word_document:
    toc: yes
    toc_depth: '3'
    code_folding: hide
  pdf_document:
    number_sections: yes
    toc: false
    toc_depth: 3
editor_options: 
  chunk_output_type: console
---


```{r}
library(DESeq2)
library("BiocParallel")
register(MulticoreParam(10))
library(magrittr)
library(PCAtools)
library(tidyverse)
library(umap)
library(patchwork)
library(httpgd)

library(here)
source(here("plot_theme.R"))
source(here("helper_functions.R"))
```


## Introduction

```{r}
dds <- readRDS(here("QC", "results", "dds_final.rds"))
mdata <- colData(dds) %>% data.frame()
svseq <- readRDS(here("QC", "results", "sva_5_final.rds"))
SVs <- svseq$sv
colnames(SVs) <- paste0("SV", 1:5)
mdata <- cbind(colData(dds) %>% data.frame() %>% select(-contains("SV")), SVs)
mdata$line <- factor(mdata$line)
dds <- DESeqDataSetFromMatrix(counts(dds),
    colData = mdata,
    design = ~ 0 + SV1 + SV2 + SV3 + SV4 + SV5 + line + group
)



# runs very long... 
# using 18 cores this literally took ~6h
# deseq_res <- DESeq(dds, parallel = TRUE)
# saveRDS(deseq_res, here("differential_gene_expression", "results","init_results.rds"))
deseq_res <- readRDS(here("differential_gene_expression", "results","init_results.rds"))
resultsNames(deseq_res)
plotDispEsts(deseq_res)

design = model.matrix(
    as.formula(paste(formula, "line + group", sep = "+")),
    colData(dds)
)
#colnames(design) <- str_remove_all(colnames(design), "group")
contrasts <- limma::makeContrasts(
    M0_comp = groupM0_stim - groupM0_ctrl,
    M1_comp = groupM1_stim - groupM1_ctrl,
    M2_comp = groupM2_stim - groupM2_ctrl,
    M1vsM0_stim = groupM1_stim - groupM0_stim, 
    M2vsM0_stim = groupM2_stim - groupM0_stim, 
    M2vsM1_stim = groupM2_stim - groupM1_stim, 
    M1vsM0_ctrl = groupM1_ctrl - groupM0_ctrl, 
    M2vsM0_ctrl = groupM2_ctrl - groupM0_ctrl, 
    M2vsM1_ctrl = groupM2_ctrl - groupM1_ctrl, 
    treat_eff_M1_vs_M0 = (groupM1_stim - groupM1_ctrl) - (groupM0_stim - groupM0_ctrl),
    treat_eff_M2_vs_M0 = (groupM2_stim - groupM2_ctrl) - (groupM0_stim - groupM0_ctrl),
    treat_eff_M2_vs_M1 = (groupM2_stim - groupM2_ctrl) - (groupM1_stim - groupM1_ctrl),
    stim_comp = (groupM0_stim + groupM1_stim + groupM2_stim)/3 - (groupM0_ctrl + groupM1_ctrl + groupM2_ctrl)/3,
    levels = design
)

# should be 0 because 15 first rows are the surrogate variables.
sum(contrasts[0:15, ]) == 0

# it is absolutely crucial, that the order of the "Levels" in contrast, is exactly the same as the
# output of resultsNames(init_deseq_res), otherwise comparisons are wrong.
stopifnot(all(rownames(contrasts) == resultsNames(deseq_res)))

M2_comp_res <- results(deseq_res, contrast = contrasts[,3])
M2_comp_res_conventional <- results(deseq_res, contrast=c("group", "M2_oxLDL", "M2_0"))
all.equal(data.frame(M2_comp_res), data.frame(M2_comp_res_conventional))

deseq_results <- parallel::mclapply(1:ncol(contrasts), function(i){
    data.frame(results(deseq_res, contrast = contrasts[, i]))
}, mc.cores = 15)
names(deseq_results) <- colnames(contrasts)


```